
DROP TABLE IF EXISTS EXCHANGE_CURRENCY;

  CREATE TABLE EXCHANGE_CURRENCY
   (
    ID bigint auto_increment,
    CODE_CURRENCY VARCHAR2(100),
	CODE_EXCHANGE VARCHAR2(100),
	VALUE_CURRENCY DECIMAL(15,4),
	FECHA VARCHAR2(20),
	UPDATE_DATE DATETIME
   );

INSERT INTO EXCHANGE_CURRENCY (CODE_CURRENCY,CODE_EXCHANGE,VALUE_CURRENCY,FECHA,UPDATE_DATE) VALUES ('USD','COMPRA',3.5654,'15/10/2020',CURRENT_TIMESTAMP);
INSERT INTO EXCHANGE_CURRENCY (CODE_CURRENCY,CODE_EXCHANGE,VALUE_CURRENCY,FECHA,UPDATE_DATE) VALUES ('USD','VENTA',4.5953,'16/10/2020',CURRENT_TIMESTAMP);
